name: Build

env:
  ProjectName: clasharp

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        configuration: [ Debug]
        os: [ windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: 6.0.x

      - name: Verify dotnet info
        run: dotnet --info

      - name: Build Solution ${{ matrix.configuration }}
        shell: pwsh
        run: ./build.ps1 -configuration "${{ matrix.configuration }}"

      - name: Upload Win App ${{ matrix.configuration }}
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: '${{ env.ProjectName }}_win_x64_${{ matrix.configuration }}'
          path: ./publish-win
          
      - name: Upload Linux App ${{ matrix.configuration }}
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: '${{ env.ProjectName }}_linux_x64_${{ matrix.configuration }}'
          path: ./publish-linux
          
          
