name: Publish

env:
  ProjectName: clasharp

on:
  push:
    tags:
      - '*'
    
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        configuration: [ Release]
        os: [ ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: 6.0.x

      - name: Verify dotnet info
        run: dotnet --info

      - name: Publish for ${{ matrix.configuration }}
        shell: bash
        run: chmod +x ./publish.sh && ./publish.sh "${{ matrix.configuration }}"

      - name: Create a new GitHub release
        uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.tag.outputs.tag }}
          prerelease: false
          draft: true
          artifacts: ./release-dir/*
